modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="realisticnpcs"
version="1.0.0"
displayName="Realistic NPCs"
authors="RobertoImI"
description='''
Adds realistic NPCs with daily routines to Minecraft
'''